name: Deploy TV Adbuy Manager

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    permissions:
      id-token: write
      contents: read

    steps:

      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload compose file
        run: |
          CONTENT=$(base64 compose-prod.yml)

          aws ssm send-command \
          --instance-ids ${{ secrets.EC2_INSTANCE_ID }} \
          --document-name "AWS-RunShellScript" \
          --parameters commands="[
          \"echo $CONTENT | base64 -d | sudo tee /opt/tv-adbuy-manager/compose-prod.yml\"
          ]"

      - name: Run Deployment Script
        run: |
          aws ssm send-command \
          --instance-ids ${{ secrets.EC2_INSTANCE_ID }} \
          --document-name "AWS-RunShellScript" \
          --parameters commands="[
          \"sudo bash /opt/tv-adbuy-manager/deploy.sh\"
          ]"
